---
title: "weights"
---

Likelihood weights routines for the analysis of Nested Sampling data

::: {.callout-note appearance="minimal"}
**Source:** [`nested_sampling/weights.py`](https://github.com/simone-romiti/lattice_data_tools/blob/main/nested_sampling/weights.py)
:::


## API Reference

#### `get_log_wL_unnormalized` {#get_log_wl_unnormalized}

```python
def get_log_wL_unnormalized(log_w: np.ndarray, log_L: np.ndarray)
```

\log(w_i*L_i), where w_i are the phase space weights, and L_i the values of the Likelihood

[View source ↗](https://github.com/simone-romiti/lattice_data_tools/blob/main/nested_sampling/weights.py#L7){.source-link style='font-size:0.8em;'}

---

#### `get_log_wL_normalized` {#get_log_wl_normalized}

```python
def get_log_wL_normalized(log_wL: np.ndarray)
```

Total weights w_i*L_i, where 1 = Z = \sum_i w_i*L_i
NOTES:     
- The normalization using Z (see implementation) is crucial.
    If not used, exp(log(w_i*L_i)) is typically compatible with 0 numerically.
- The partition function is Z = \sum_i w_i * L_i
    As a function of the phase space volume X_i, the w_i and L_i are:
    - very small in almost all the range
    - mildly overlapping 
    Therefore, if we first exponentiate their logs and sum them naively, we get 0 on all the interval.  
    Solution: we work with logarithms all the time.

[View source ↗](https://github.com/simone-romiti/lattice_data_tools/blob/main/nested_sampling/weights.py#L13){.source-link style='font-size:0.8em;'}

---

#### `get_log_Z_curve` {#get_log_z_curve}

```python
def get_log_Z_curve(log_wL_normalized: np.ndarray)
```

The partition function is normalized to 1.
The total weights w_i*L_i are the discrete version of the probability density function.
The cumulative sum of the total weights gives use the cumulative density function. This function returns the log of that curve.

[View source ↗](https://github.com/simone-romiti/lattice_data_tools/blob/main/nested_sampling/weights.py#L33){.source-link style='font-size:0.8em;'}

---

#### `get_log_rho` {#get_log_rho}

```python
def get_log_rho(log_X: np.ndarray, log_S: np.ndarray)
```

Logarithm \log(\rho(S)), where \rho(S) is the the density of states: \rho(S) = dS/dX
The derivative is computed in terms of the derivatives of \log(S) with respect to \log(X)
NOTE: The action plays the analogous role of the energy in statistical mechanics

[View source ↗](https://github.com/simone-romiti/lattice_data_tools/blob/main/nested_sampling/weights.py#L51){.source-link style='font-size:0.8em;'}

---

#### `get_idx_pruned_interval` {#get_idx_pruned_interval}

```python
def get_idx_pruned_interval(log_wL_normalized: np.ndarray, eps_wL: float)
```

At fixed \beta, we have the total weights for all values of the phase space variable "X".
In general however, only a small subset of values of the action "S" really contributes to the integral,
thus we can prune the interval such that wL > eps_wL (a custom threshold).

This function retunrs the indices corresponding to the pruning.
They should be used to prune all the other variables used in the analysis at that \beta,
such as the observables arrays.

[View source ↗](https://github.com/simone-romiti/lattice_data_tools/blob/main/nested_sampling/weights.py#L63){.source-link style='font-size:0.8em;'}

---

#### `get_average_observable` {#get_average_observable}

```python
def get_average_observable(log_wL_normalized: np.ndarray, obs: np.ndarray)
```

Average value of an observable O, where:

- (w*L)_i are the total weights (normalized to 1) at each value of the phase space variable X_i
- \log(O_i) are the logs of the observable computed at those points

[View source ↗](https://github.com/simone-romiti/lattice_data_tools/blob/main/nested_sampling/weights.py#L82){.source-link style='font-size:0.8em;'}

---
