---
title: "bounding_methods"
---

Bounding methods for a_\mu, for a single bootstrap sample

::: {.callout-note appearance="minimal"}
**Source:** [`gm2/HVP/bounding_methods.py`](https://github.com/simone-romiti/lattice_data_tools/blob/main/gm2/HVP/bounding_methods.py)
:::


## API Reference

#### `ZeroTail` {#zerotail}

```python
def ZeroTail(window: Literal['SD', 'W', 'LD', 'full'], a_fm: float, V: np.ndarray, K: np.ndarray, Z_ren: float, t0: int, strategy='trapezoidal') -> float
```

Calculation of a_\mu as \int_{0}^{t_0} t^2 K(t) Z^2 V(t)
In other word, V(t) is replaced with 0 from t=t0 onwards
NOTE: all quantities should be in lattice units

Args:
    window (str): name of time modulator
    a_fm (float): lattice spacing in [fm]
    K (np.ndarray): values of the Kernel: K(0), K(1), ..., K(T_max)
    V (np.ndarray): values of the correlator: V(0), V(1), ..., V(T_max)
    NOTE: 
        the correlator should be "bare" (i.e. not renormalized),
        and should already include the charge factors

    Z_ren: renormalization constant for the vector current: Z_A for tm and Z_V for OS
    t0 (int): value (included) of t after which we set V=0
    strategy (str): integration strategy

Returns:
    float: value of the integral

[View source ↗](https://github.com/simone-romiti/lattice_data_tools/blob/main/gm2/HVP/bounding_methods.py#L10){.source-link style='font-size:0.8em;'}

---

#### `MesonPair` {#mesonpair}

```python
def MesonPair(M_meson: float, L: float, window: Literal['SD', 'W', 'LD', 'full'], a_fm: float, V: np.ndarray, K: np.ndarray, Z_ren: float, t0: int, strategy='trapezoidal') -> float
```

Calculation of a_\mu as \int_{0}^{t_0} t^2 K(t) Z^2 V(t) + \int_{t0}^{T_max} A e^{-E_{\pi\pi} t}
In other words, we replace the tail of the correlator with the 2 pions state with minimum momentum on the lattice: p_min=(2\pi)/L
NOTE: this is necessary because 2 pions at rest can't have total angular momentum 1, as the vector current in the correlator V(t).

Args:
    M_meson (float): meson mass, e.g. pion mass
    L (float): volume
    V (np.ndarray): bare vector-vector correlator
    K (np.ndarray): precomputed values of the Kernel K(t)
    Z_ren (float): renormalization constant of the vector current
    t0 (int): separation point of the 2 contributions to the integral
    strategy (str, optional): numerical integration strategy. Defaults to "trapezoidal".

Returns:
    float: value of the integral

[View source ↗](https://github.com/simone-romiti/lattice_data_tools/blob/main/gm2/HVP/bounding_methods.py#L38){.source-link style='font-size:0.8em;'}

---

#### `M_eff_t0_Tail` {#m_eff_t0_tail}

```python
def M_eff_t0_Tail(M_eff: np.ndarray, window: Literal['SD', 'W', 'LD', 'full'], a_fm: float, V: np.ndarray, K: np.ndarray, Z_ren: float, t0: int, strategy='trapezoidal') -> float
```

Calculation of a_\mu as \int_{0}^{t_0} t^2 K(t) Z^2 V(t) + \int_{t0}^{T_max} A e^{- M_eff(t0)* t}
In other words, we replace the tail of the correlator with the state with energy equal to the effective matt at t=t0

The constant "A" is chosen such that the tail matches the correlator at t0, viz. A = C(t0)*e^{+M_eff(t0)*t}

Args:
    Meff (np.ndarray): effective mass curve of the correlator V(t)
    V (np.ndarray): bare vector-vector correlator V(t)
    K (np.ndarray): precomputed values of the Kernel K(t)
    Z_ren (float): renormalization constant of the vector current
    t0 (int): separation point of the 2 contributions to the integral
    strategy (str, optional): numerical integration strategy. Defaults to "trapezoidal".

Returns:
    float: value of the integral

[View source ↗](https://github.com/simone-romiti/lattice_data_tools/blob/main/gm2/HVP/bounding_methods.py#L68){.source-link style='font-size:0.8em;'}

---

### `FiniteVolume` {#finitevolume}

```python
class FiniteVolume
```

[View source ↗](https://github.com/simone-romiti/lattice_data_tools/blob/main/gm2/HVP/bounding_methods.py#L100){.source-link style='font-size:0.8em;'}

---

#### `FiniteVolume.Gounaris_Sakurai` {#finitevolume-gounaris_sakurai}

```python
def Gounaris_Sakurai(V_PP: np.ndarray, t0: int, window: Literal['SD', 'W', 'LD', 'full'], a_fm: float, V_lat: np.ndarray, K: np.ndarray, Z_ren: float, strategy: str='trapezoidal')
```

Calculation of a_\mu as \int_{0}^{t_0} t^2 K(t) Z^2 V_lat(t) + \int_{t0}^{T_max} t^2 K(t) V_{\pi\pi}(t)
In other words, we replace the tail of the correlator with a model,
assuming that is gets the leading contribution from \pi\pi states.

All the inputs are in lattice units

[View source ↗](https://github.com/simone-romiti/lattice_data_tools/blob/main/gm2/HVP/bounding_methods.py#L102){.source-link style='font-size:0.8em;'}

---
