---
title: "effective_curves"
---

::: {.callout-note appearance="minimal"}
**Source:** [`effective_curves.py`](https://github.com/simone-romiti/lattice_data_tools/blob/main/effective_curves.py)
:::


## API Reference

#### `get_m_eff_log` {#get_m_eff_log}

```python
def get_m_eff_log(C: np.ndarray) -> np.ndarray
```

Effective mass curve

log: log(C[t]/C[t+1])

Args:
    C (np.ndarray): Correlator C(t)

Returns:
    np.ndarray: M_eff(t) = log(C(t)/C(t+1))

.. ldt-id:: EFF-get_m_eff_log

[View source ↗](https://github.com/simone-romiti/lattice_data_tools/blob/main/effective_curves.py#L6){.source-link style='font-size:0.8em;'}

---

#### `get_A_eff_log` {#get_a_eff_log}

```python
def get_A_eff_log(C: np.ndarray, m_eff: np.ndarray) -> np.ndarray
```

Effective amplitude curve : A_eff(t) = C(t)/exp(-m_eff(t)*t)

Args:
    C (np.ndarray): Correlator C(t)
    m_eff (np.ndarray): effective mass curve m_eff(t)

Returns:
    np.ndarray: M_eff(t) = log(C(t)/C(t+1)), A_eff = C(t)*e^{m_eff*t}

.. ldt-id:: EFF-get_A_eff_log

[View source ↗](https://github.com/simone-romiti/lattice_data_tools/blob/main/effective_curves.py#L24){.source-link style='font-size:0.8em;'}

---

#### `get_m_eff_bkw` {#get_m_eff_bkw}

```python
def get_m_eff_bkw(C: np.ndarray, T: int, p: int, avoid_instability=False)
```

Effective mass including the backward signal
see eq. 6.57 of Gattringer & Lang

avoid_instability:
    flag relative to the case C(t)/C(t+1) <= 1 (statistical fluctuation)
    if True AND t>=1,
    M_eff(t) is replaced with the previous value M_eff(t-1)

.. ldt-id:: EFF-get_m_eff_bkw

[View source ↗](https://github.com/simone-romiti/lattice_data_tools/blob/main/effective_curves.py#L45){.source-link style='font-size:0.8em;'}

---

#### `get_A_eff_bkw` {#get_a_eff_bkw}

```python
def get_A_eff_bkw(C: np.ndarray, m_eff: np.ndarray, T: int, p: int)
```

Effective Amplitude including the backward signal
see eq. 6.57 of Gattringer & Lang

.. ldt-id:: EFF-get_A_eff_bkw

[View source ↗](https://github.com/simone-romiti/lattice_data_tools/blob/main/effective_curves.py#L86){.source-link style='font-size:0.8em;'}

---

#### `get_m_eff` {#get_m_eff}

```python
def get_m_eff(C: np.ndarray, strategy: Literal['log', 'cosh', 'sinh'], T=None, avoid_instability=False) -> np.ndarray
```

Effective mass curve from the correlator

Args:
    C (np.ndarray): correlator C(t)
    strategy (str): computation strategy

Raises:
    ValueError: if strategy is not in the list of supported types

Returns:
    np.ndarray: array of effective mass values M_eff(t)

.. ldt-id:: EFF-get_m_eff

[View source ↗](https://github.com/simone-romiti/lattice_data_tools/blob/main/effective_curves.py#L100){.source-link style='font-size:0.8em;'}

---

#### `get_A_eff` {#get_a_eff}

```python
def get_A_eff(C: np.ndarray, m_eff: np.ndarray, strategy: Literal['log', 'cosh', 'sinh'], T: int=None) -> np.ndarray
```

Effective Amplitude curve from the correlator

Args:
    C (np.ndarray): correlator C(t)
    m_eff (np.ndarray): effective mass m_eff(t)

    strategy (str): computation strategy

Raises:
    ValueError: if strategy is not in the list of supported types

Returns:
    np.ndarray: array of effective mass values M_eff(t)

.. ldt-id:: EFF-get_A_eff

[View source ↗](https://github.com/simone-romiti/lattice_data_tools/blob/main/effective_curves.py#L129){.source-link style='font-size:0.8em;'}

---

#### `get_dm_eff_log` {#get_dm_eff_log}

```python
def get_dm_eff_log(C0: np.ndarray, dC: np.ndarray) -> np.ndarray
```

Effective mass correction assuming $C(t) = A e^{-M t}$

Args:
    C0 (np.ndarray): Correlator $C(t)$
    dC (np.ndarray): Correction to the correlator $C_0(t)$

Returns:
    np.ndarray: `dM_eff(t) = - [R(t+1) - R(t)], where R(t) = dC(t)/C0(t)`

.. ldt-id:: EFF-get_dm_eff_log

[View source ↗](https://github.com/simone-romiti/lattice_data_tools/blob/main/effective_curves.py#L160){.source-link style='font-size:0.8em;'}

---

#### `get_dm_eff_bkw` {#get_dm_eff_bkw}

```python
def get_dm_eff_bkw(C0: np.ndarray, dC: np.ndarray, M0_eff: np.ndarray, T: int, p: int)
```

Effective mass correction including the backward signal
see eq. 11 of:
https://journals.aps.org/prd/abstract/10.1103/PhysRevD.106.014502

C0 (np.ndarray): Correlator C(t)
dC (np.ndarray): correction to the correlator C_0(t)
M0_eff (np.ndarray):
    effective mass curve for the C_0 correlator.
    NOTE: It is not computed automatically internally because
          the user may want to fix it for all "t".
          In this case, pass M0_eff as a constant array

.. ldt-id:: EFF-get_dm_eff_bkw

[View source ↗](https://github.com/simone-romiti/lattice_data_tools/blob/main/effective_curves.py#L177){.source-link style='font-size:0.8em;'}

---

#### `get_dm_eff` {#get_dm_eff}

```python
def get_dm_eff(C0: np.ndarray, dC: np.ndarray, M0_eff: np.ndarray, strategy: Literal['log', 'cosh', 'sinh'], T=None) -> np.ndarray
```

Effective curve for a mass correction the correlator

Args:
    C0 (np.ndarray): correlator C_0(t) in the free theory (e.g. isoQCD)
    dC (np.ndarray): correction to the correlator $C_0(t)$
    strategy (str): computation strategy

Raises:
    ValueError: if strategy is not in the list of supported types

Returns:
    np.ndarray: array of effective mass values M_eff(t)

.. ldt-id:: EFF-get_dm_eff

[View source ↗](https://github.com/simone-romiti/lattice_data_tools/blob/main/effective_curves.py#L213){.source-link style='font-size:0.8em;'}

---

#### `fit_eff_curve` {#fit_eff_curve}

```python
def fit_eff_curve(y_eff: np.ndarray, dy_eff: np.ndarray) -> np.float128
```

Fit the effective curve (in the plateau) to a constant

Args:
    y_eff (np.ndarray): array of values for y_eff(t) ONLY in the plateau
    dy_eff (np.ndarray): uncertainty on y_eff(t) in that plateau interval

    NOTE: tmin and tmax are not passed because it is assumed assumed to have slices the arrays in the plateau interval

Returns:
    float: best fit value of y_eff

.. ldt-id:: EFF-fit_eff_curve

[View source ↗](https://github.com/simone-romiti/lattice_data_tools/blob/main/effective_curves.py#L243){.source-link style='font-size:0.8em;'}

---

#### `fit_eff_mass` {#fit_eff_mass}

```python
def fit_eff_mass(m_eff: np.ndarray, dm_eff: np.ndarray) -> np.float128
```

alias for the fit to a generic effective curve

.. ldt-id:: EFF-fit_eff_mass

[View source ↗](https://github.com/simone-romiti/lattice_data_tools/blob/main/effective_curves.py#L266){.source-link style='font-size:0.8em;'}

---

#### `get_leading_curve` {#get_leading_curve}

```python
def get_leading_curve(t: np.ndarray, A0: np.float128, m0: np.float128, p: int=None, T: int=None)
```

[View source ↗](https://github.com/simone-romiti/lattice_data_tools/blob/main/effective_curves.py#L276){.source-link style='font-size:0.8em;'}

---
