print("""
      ----------------------------------------
      Reading confs: mistunings in the valence
      ----------------------------------------
      """
      )


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

from lattice_data_tools.bootstrap import BootstrapSamples
from lattice_data_tools.dictionaries import NestedDict
from lattice_data_tools.bootstrap import uncorrelated_confs_to_bts, parametric_gaussian_bts
from lattice_data_tools.io import with_dill, with_yaml

from local_libs import read_bin

ens_info = with_yaml.load("ensembles.yaml")
aux_dir = ens_info["data"]["auxiliary"]

print("# Reading mistuning data")

delta_VKVK_valence_dict = NestedDict()
ens_names = ens_info["data"]["ens_list"]
mistunings_valence_dir = ens_info["data"]["VkVk_slopes_mlight_valence"]

N_bts = ens_info["N_bts"]
RNG_seed = ens_info["RNG_seed"]
np.random.seed(RNG_seed)

isoQCD_point = pd.read_csv("isoQCD_point.csv", sep=r"\s+", comment='#')

f_pi_list = ens_info["data"]["f_pi_MeV"]
for f_pi in f_pi_list:
    print(f"f_pi:{f_pi}")
    fpi_dir = f"{aux_dir}/fpi_{f_pi}_MeV/"
    os.makedirs(fpi_dir, exist_ok=True)
    #
    delta_mu_l_dict = with_dill.load(f"{fpi_dir}/dmu_l.pkl")
    for i_ens, ens_name in enumerate(ens_names):
        print("Ensemble: ", ens_name)
        en = (ens_name.split(".")[0]+ens_name.split(".")[2])[1:]
        mistunings_sea_dir =f'{ens_info["data"]["VkVk_slopes_mlight_sea"]}/'
        delta_mu_l = delta_mu_l_dict[ens_name]
        T = ens_info[ens_name]["T"]
        T_half = T//2
        T_ext = T_half+1 # last dimension runs over time: T/2+1 values
        times = np.arange(0, T_ext)
        for fermion_type in ["OS", "tm"]:
            print("  Fermions: ", fermion_type)
            if en == "B96":
                delta_VKVK_valence_dict[ens_name][fermion_type] = BootstrapSamples.zeros(N_bts=N_bts, shape=(T_ext))
            else:
                # valence correction (bare: renormalization constant, alpha_em, etc. applied later)
                data_slope_valence = read_bin(f"{mistunings_valence_dir}/{en}/VkVk_{fermion_type}_mistuning_{en}.bin")["confs"]
                valence_confs = np.average(data_slope_valence, axis=0)
                assert valence_confs.shape[1] == T_ext, f"Unexpected time extent in valence mistuning data for ensemble {ens_name}, fermion type {fermion_type}"
                valence_bts = BootstrapSamples([uncorrelated_confs_to_bts(valence_confs[:,t], N_bts=N_bts, seed=RNG_seed) for t in times]).transpose()
                print("    valence:", valence_confs.shape, " --> ", valence_bts.shape)
                # sea correction (bare: renormalization constant, alpha_em, etc. applied later)
                data_slope_sea = read_bin(f"{mistunings_sea_dir}/{en}_{fermion_type}_vkvk_sea-ml_derivative_resampled.bin")["confs"]
                sea_confs = np.average(data_slope_sea, axis=0) # NOTE: not real "configurations", just bootstrap samples generated by G. Gagliardi
                assert sea_confs.shape[1] == T_ext, f"Unexpected time extent in sea mistuning data for ensemble {ens_name}, fermion type {fermion_type}"
                sea_bts = BootstrapSamples(sea_confs[0:(N_bts+1),:])
                print("    sea:", sea_confs.shape, " --> ", sea_bts.shape)
                # calculating the total correction: valence+sea
                delta_VKVK_valence_dict[ens_name][fermion_type] = delta_mu_l[:, np.newaxis]*(valence_bts + sea_bts)
    #-----------
    os.makedirs(f"{fpi_dir}", exist_ok=True)
    with_dill.dump(delta_VKVK_valence_dict, f"{fpi_dir}/dVKVK_ml_valence_plus_sea_bts.pkl")
#---


