---
title: "trajectory"
---

Routines for fitting a function $f: \mathbb{R}^n \to \mathbb{R}^m$

This file contains functions for fitting multi-dimensional functions
of many variables. This is done using the maximum likelyhood principle
and a "trajectory method":
the function $\vec{y} = \vec{f}(\vec{x})$ is thought as
a trajectory $\vec{z}(t)$ in a n+m dimensional space:

$$z_i = x_i \, , \, i=1,...,n$$
$$z_i = y_i \, , \, i=n+1,...,m$$

The fit minimizes the distance of this trajectory
from the theoretical expectation.

.. ldt-id:: FIT-trajectory-module

::: {.callout-note appearance="minimal"}
**Source:** [`fit/trajectory.py`](https://github.com/simone-romiti/lattice_data_tools/blob/main/fit/trajectory.py)
:::


## API Reference

#### `fit_trajectory` {#fit_trajectory}

```python
def fit_trajectory(ansatz, x: np.ndarray, ex: np.ndarray, y: np.ndarray, ey: np.ndarray, guess: np.ndarray, method='BFGS', Cov_inv=None)
```

Fit a function f: \mathbb{R}^n \to \mathbb{R}^m with the trajectory method

Args:
    ansatz : function f(x, p): x=1d array, p=1d array, returns 1d array
    x (np.ndarray): x values: array of size (N_pts, n)
    ex (np.ndarray): errors on x values: array of size (N_pts, n)
    y (np.ndarray): y values: array of size (N_pts, m)
    ey (np.ndarray): errors on y values: array of size (N_pts, m)
    guess (np.ndarray): guesses for the ansatz of the fit
    maxiter (int, optional): _description_. Defaults to 10000.
    method (str, optional): _description_. Defaults to "BFGS".
    Cov_inv: inverse covariance matrix estimate (e.g. from a fit on the bootstrap mean)

Returns:
    dict: Dictionary with the information about the fit

.. ldt-id:: FIT-fit_trajectory

[View source ↗](https://github.com/simone-romiti/lattice_data_tools/blob/main/fit/trajectory.py#L21){.source-link style='font-size:0.8em;'}

---
